apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers/cert-manager
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 1h
  retryInterval: 1m
  timeout: 5m
