apiVersion: v1
sshGatewayHostKey:
  kind: secret
  name: ssh-gateway-host-key
workspace:
  runtime:
    containerdRuntimeDir: /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io # k3s settings
    containerdSocket: /run/k3s/containerd/containerd.sock # k3s settings
    fsShiftMethod: shiftfs # This is only compatible with Ubuntu 20.04/cgroup v1 - Ubuntu 22.04 uses cgroup v2
