apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: https-certificates
  namespace: gitpod
  labels:
    app: gitpod
spec:
  secretName: https-certificates
  issuerRef:
    name: gitpod-issuer
    kind: ClusterIssuer
  dnsNames: []
  secretTemplate:
    labels:
      app: gitpod
