---
apiVersion: v1
kind: Namespace
metadata:
  name: scaleway-cert-manager
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: scaleway-cert-manager
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/scaleway/cert-manager-webhook-scaleway.git
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/deploy/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: scaleway-cert-manager
  namespace: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: deploy/scaleway-webhook
      version: v0.0.1"
      sourceRef:
        kind: GitRepository
        name: scaleway-cert-manager
        namespace: flux-system
      interval: 12h
  values:
    installCRDs: true
    extraArgs:
       - secret.accessKey=SCWTAZN04VMSA6QRHQRV
       - secret.secretKey=80b4cd09-6c9c-4e4a-9d4c-35a3a05acf89
