ARG INSTALLER_VERSION
FROM eu.gcr.io/gitpod-core-dev/build/installer:${INSTALLER_VERSION}
ARG INSTALLER_VERSION
LABEL org.opencontainers.image.version "${INSTALLER_VERSION}"
LABEL org.opencontainers.image.description "Gitpod Installer"
