name: Lint
on:
  - pull_request
  - push
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch-depth is required

      - uses: wagoid/commitlint-github-action@v5

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ludeeus/action-shellcheck@master

  terraform_dirs:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.dirs.outputs.dirs }}
    steps:
      - uses: actions/checkout@v3

      - name: Get terraform module folders
        id: dirs
        run: |
          DIRS=$(jq -MncR '[inputs]' <<< $(ls -d infrastructure/*/*))
          echo "dirs=$DIRS" >> $GITHUB_OUTPUT

  terraform:
    runs-on: ubuntu-latest
    needs:
      - terraform_dirs
    strategy:
      fail-fast: true
      matrix:
        # Only checks modules, not examples
        dir: ${{ fromJSON(needs.terraform_dirs.outputs.dirs) }}
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      # Not used, but required for the validation tests
      - name: Create private key
        run: |
          mkdir -p "${HOME}/.ssh"
          ssh-keygen -t dsa -N "my passphrase" -C "test key" -f "${HOME}/.ssh/id_rsa"

      - name: Terraform fmt
        run: terraform fmt -recursive -check

      - name: Terraform init
        run: terraform -chdir=${{ matrix.dir }} init

      - name: Terraform validate
        run: terraform -chdir=${{ matrix.dir }} validate
